name: OddItem
main: info.somethingodd.bukkit.OddItem.OddItem
version: 0.6.2
website: http://bukkit.somethingodd.info
author: petteyg359
description: >
             Item database stuff.
commands:
  odditem:
    usage: |
           /<command> [aliases item]|[info]|[list]|[reload]
           aliases - Lists aliases for item
           info - Shows number of items loaded.
           list - Lists items.
           reload - Reloads item data.
